In [1]:
!pip install multiprocesspandas
!pip install sentencepiece

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.0/109.0 kB 553.9 kB/s eta 0:00:00a 0:00:01
  Attempting uninstall: multiprocess
    Found existing installation: multiprocess 0.70.14
    Uninstalling multiprocess-0.70.14:
      Successfully uninstalled multiprocess-0.70.14
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pathos 0.3.0 requires multiprocess>=0.70.14, but you have multiprocess 0.70.11.1 which is incompatible.


# CV Split

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedGroupKFold
from multiprocesspandas import applyparallel
from tqdm import tqdm

In [8]:
N_SPLITS = 5
DATA_PATH = '/kaggle/input/learning-equality-curriculum-recommendations/'

In [5]:
topic_df = pd.read_csv(DATA_PATH + 'topics.csv')
content_df = pd.read_csv(DATA_PATH + 'content.csv')
corr_df = pd.read_csv(DATA_PATH + 'correlations.csv')

topic_df_non_source = topic_df[topic_df['category']!='source'].reset_index(drop=True)
topic_df_non_source['stratify'] = topic_df_non_source['category'] + \
topic_df_non_source['language'] + topic_df_non_source['description'].apply(lambda x: str(isinstance(x, str))) + \
topic_df_non_source['has_content'].apply(str)

In [6]:
topic_df_non_source.head()

id                                   title  \
0  t_000095e03056  Unit 3.3 Enlargements and Similarities   
1  t_0008768bdee6                       100 સુધીનો સરવાળો   
2  t_0008a1bd84ba               12. 20: Bird Reproduction   
3  t_000d1fb3f2f5                      2.1.2 - Logarithms   
4  t_00102869fbcb                  Triangles and polygons   

                                         description channel      category  \
0                                                NaN  b3f329       aligned   
1       37 અને 49 જેવી બે-અંકની સંખ્યાઓ ઉમેરતા શીખો.  5223e0  supplemental   
2                                                NaN  ebc86c  supplemental   
3                                                NaN  e77b55       aligned   
4  Learning outcomes: students must be able to so...  a91e32       aligned   

   level language          parent  has_content                 stratify  
0      2       en  t_aa32fb6252dc        False      alignedenFalseFalse  
1      4       gu  t_0da7a331d666         True   supplementalguTrueTrue  
2      5       en  t_c44ac9711007         True  supplementalenFalseTrue  
3      5       en  t_b897d168db90         True       alignedenFalseTrue  
4      3       en  t_039cecc12bb8         True        alignedenTrueTrue

In [9]:
kf = StratifiedGroupKFold(n_splits=N_SPLITS)
folds = list(kf.split(topic_df_non_source, y=topic_df_non_source['stratify'], groups=topic_df_non_source["channel"]))
topic_df_non_source['fold'] = -1

/opt/conda/lib/python3.7/site-packages/sklearn/model_selection/_split.py:880: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  UserWarning,


In [10]:
folds

[(array([    1,     2,     3, ..., 33481, 33482, 33484]),
  array([    0,    10,    12, ..., 33479, 33480, 33483])),
 (array([    0,     1,     2, ..., 33482, 33483, 33484]),
  array([    5,     7,     8, ..., 33473, 33478, 33481])),
 (array([    0,     2,     3, ..., 33482, 33483, 33484]),
  array([    1,    11,    24, ..., 33470, 33471, 33477])),
 (array([    0,     1,     5, ..., 33481, 33483, 33484]),
  array([    2,     3,     4, ..., 33445, 33446, 33482])),
 (array([    0,     1,     2, ..., 33481, 33482, 33483]),
  array([    6,    14,    17, ..., 33474, 33475, 33484]))]

In [ ]:
for fold, (train_idx, val_idx) in enumerate(folds):
    

# What to do next?
* Learn KFold